import os
import logging
from mailersend import emails

logger = logging.getLogger(__name__)

def send_report_email(provider_name, provider_phone, reason, other_reason=None, user_ip=None):
    """
    Send a report email to support@connectyou.pro using MailerSend
    
    Args:
        provider_name: Name of the reported provider
        provider_phone: Phone number of the reported provider
        reason: Selected reason for the report
        other_reason: Additional details if reason is 'other'
        user_ip: IP address of the reporting user
        
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    
    api_key = os.environ.get('MAILERSEND_API_KEY')
    if not api_key:
        logger.error("MAILERSEND_API_KEY not found in environment variables")
        return False
    
    try:
        # Initialize MailerSend
        mailer = emails.NewEmail(api_key)
        
        # Format the reason text
        reason_text = {
            'incorrect_information': 'Incorrect Information',
            'poor_service': 'Poor Service Quality',
            'unprofessional': 'Unprofessional Behavior',
            'scam_fraud': 'Scam or Fraud',
            'safety_concerns': 'Safety Concerns',
            'other': 'Other'
        }.get(reason, reason)
        
        # Build email content
        subject = f"Service Provider Report: {provider_name}"
        
        # Create detailed email body
        email_body = f"""
A new service provider report has been submitted through the ConnectYou platform.

REPORTED PROVIDER DETAILS:
- Provider Name: {provider_name}
- Phone Number: {provider_phone}

REPORT DETAILS:
- Reason for Report: {reason_text}
"""
        
        if reason == 'other' and other_reason:
            email_body += f"- Additional Details: {other_reason}\n"
        
        if user_ip:
            email_body += f"- Reporter IP: {user_ip}\n"
        
        email_body += f"""
Please review this report and take appropriate action if necessary.

This report was automatically generated by the ConnectYou Service Provider Directory.
"""
        
        # Define the email
        mail_body = {}
        
        mail_from = {
            "name": "ConnectYou Directory",
            "email": "noreply@trial-3yxj6ljz7xl4do2r.mlsender.net"
        }
        
        recipients = [
            {
                "name": "Support Team",
                "email": "valuesnip.com@gmail.com"
            }
        ]
        
        # Create HTML version
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2 style="color: #007bff;">Service Provider Report</h2>
                <p>A new service provider report has been submitted through the ConnectYou platform.</p>
                
                <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <h3 style="margin-top: 0; color: #495057;">Reported Provider Details:</h3>
                    <p><strong>Provider Name:</strong> {provider_name}</p>
                    <p><strong>Phone Number:</strong> {provider_phone}</p>
                </div>
                
                <div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <h3 style="margin-top: 0; color: #856404;">Report Details:</h3>
                    <p><strong>Reason for Report:</strong> {reason_text}</p>
                    {f'<p><strong>Additional Details:</strong> {other_reason}</p>' if reason == 'other' and other_reason else ''}
                    {f'<p><strong>Reporter IP:</strong> {user_ip}</p>' if user_ip else ''}
                </div>
                
                <p style="margin-top: 30px;">Please review this report and take appropriate action if necessary.</p>
                <p style="color: #6c757d; font-size: 14px;">This report was automatically generated by the ConnectYou Service Provider Directory.</p>
            </div>
        </body>
        </html>
        """
        
        # Set email content
        mailer.set_mail_from(mail_from, mail_body)
        mailer.set_mail_to(recipients, mail_body)
        mailer.set_subject(subject, mail_body)
        mailer.set_plaintext_content(email_body, mail_body)
        mailer.set_html_content(html_body, mail_body)
        
        # Send the email
        response = mailer.send(mail_body)
        
        # Log the actual response for debugging
        logger.info(f"MailerSend response: {response}")
        
        if response:
            logger.info(f"Report email sent successfully for provider: {provider_name}")
            return True
        else:
            logger.error(f"Failed to send report email for provider: {provider_name}")
            return False
            
    except Exception as e:
        logger.error(f"Error sending report email: {str(e)}")
        return False