#!/usr/bin/env python3
"""
Environment Setup Script for ConnectYou AI Chat
Creates .env file with configuration
"""

import os
import sys

def create_env_file():
    """Create .env file with user input"""
    
    print("🚀 ConnectYou AI Chat Environment Setup")
    print("=" * 50)
    print("This will create a .env file with your configuration.")
    print("You can also set these as environment variables instead.")
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return False
    
    config = {}
    
    # AI Provider Selection
    print("1️⃣  Choose AI Provider:")
    print("   a) Claude (Anthropic) - Most intelligent, $3-15/month")
    print("   b) OpenAI (ChatGPT) - Popular choice, $0.50-30/month") 
    print("   c) Google Gemini - Free tier available, $1-7/month")
    print("   d) Skip (use local fallback mode)")
    
    provider_choice = input("Select (a/b/c/d) [a]: ").lower().strip() or 'a'
    
    if provider_choice == 'd':
        print("⚠️  Skipping AI configuration - will use local fallback mode")
        config['AI_PROVIDER'] = 'local'
    else:
        provider_map = {'a': 'claude', 'b': 'openai', 'c': 'google'}
        provider = provider_map.get(provider_choice, 'claude')
        config['AI_PROVIDER'] = provider
        
        print(f"Selected: {provider.title()}")
        print()
        
        # Get API key for chosen provider
        if provider == 'claude':
            print("🔑 Claude API Key:")
            print("   1. Go to: https://console.anthropic.com/")
            print("   2. Create account and add billing")
            print("   3. Go to API Keys section")
            print("   4. Create new API key")
            api_key = input("   Enter Claude API key (sk-ant-...): ").strip()
            if api_key:
                config['CLAUDE_API_KEY'] = api_key
                config['AI_MODEL'] = 'claude-3-sonnet-20240229'
                
        elif provider == 'openai':
            print("🔑 OpenAI API Key:")
            print("   1. Go to: https://platform.openai.com/api-keys")
            print("   2. Create account and add billing")
            print("   3. Create new secret key")
            api_key = input("   Enter OpenAI API key (sk-...): ").strip()
            if api_key:
                config['OPENAI_API_KEY'] = api_key
                config['AI_MODEL'] = 'gpt-3.5-turbo'
                
        elif provider == 'google':
            print("🔑 Google Gemini API Key:")
            print("   1. Go to: https://makersuite.google.com/app/apikey")
            print("   2. Create API key (free tier available)")
            api_key = input("   Enter Google API key (AI...): ").strip()
            if api_key:
                config['GOOGLE_API_KEY'] = api_key
                config['AI_MODEL'] = 'gemini-pro'
    
    print()
    
    # Twilio SMS Configuration
    print("2️⃣  SMS Configuration (Twilio):")
    print("   This is needed to contact providers automatically")
    print("   Get credentials from: https://console.twilio.com/")
    
    setup_sms = input("   Configure SMS? (y/N): ").lower().strip()
    
    if setup_sms == 'y':
        twilio_sid = input("   Twilio Account SID (AC...): ").strip()
        twilio_token = input("   Twilio Auth Token: ").strip()
        twilio_phone = input("   Twilio Phone Number (+1234567890): ").strip()
        
        if twilio_sid and twilio_token and twilio_phone:
            config['TWILIO_ACCOUNT_SID'] = twilio_sid
            config['TWILIO_AUTH_TOKEN'] = twilio_token
            config['TWILIO_PHONE_NUMBER'] = twilio_phone
        else:
            print("   ⚠️  Incomplete SMS configuration")
    
    print()
    
    # Advanced settings
    print("3️⃣  Advanced Settings:")
    
    max_tokens = input("   Max tokens (1024): ").strip() or "1024"
    temperature = input("   Temperature 0-2 (0.7): ").strip() or "0.7"
    
    config['AI_MAX_TOKENS'] = max_tokens
    config['AI_TEMPERATURE'] = temperature
    
    # Generate secret key
    import secrets
    config['SESSION_SECRET'] = secrets.token_urlsafe(32)
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write("# ConnectYou AI Chat Configuration\n")
            f.write("# Generated by setup_env.py\n\n")
            
            for key, value in config.items():
                f.write(f"{key}={value}\n")
        
        print()
        print("✅ Configuration saved to .env file!")
        print()
        print("Next steps:")
        print("1. Start your application: python main.py")
        print("2. Test the AI chat on your website")
        print("3. Check admin panel for configuration status")
        print()
        print("💡 You can always edit the .env file or use the admin panel to update settings")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def load_env_file():
    """Load environment variables from .env file"""
    if not os.path.exists('.env'):
        return
    
    try:
        with open('.env', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key] = value
    except Exception as e:
        print(f"Warning: Could not load .env file: {e}")

if __name__ == "__main__":
    success = create_env_file()
    
    if success:
        print("\n🎉 Setup complete!")
        
        # Ask if they want to start the server
        start_server = input("\nStart the server now? (y/N): ").lower().strip()
        if start_server == 'y':
            print("Starting server...")
            load_env_file()  # Load the new environment
            os.system("python main.py")