import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

def send_simple_report_email(provider_name, provider_phone, reason, other_reason=None, user_ip=None):
    """
    Send a simple report email using SMTP
    """
    try:
        # Email configuration - using Gmail SMTP as fallback
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        
        # For now, we'll use a simple text-based approach
        # In production, you'd want proper SMTP credentials
        
        # Format the reason text
        reason_text = {
            'incorrect_information': 'Incorrect Information',
            'poor_service': 'Poor Service Quality', 
            'unprofessional': 'Unprofessional Behavior',
            'scam_fraud': 'Scam or Fraud',
            'safety_concerns': 'Safety Concerns',
            'other': 'Other'
        }.get(reason, reason)
        
        # Create email content
        subject = f"Service Provider Report: {provider_name}"
        
        body = f"""
A new service provider report has been submitted through the ConnectYou platform.

REPORTED PROVIDER DETAILS:
- Provider Name: {provider_name}
- Phone Number: {provider_phone}

REPORT DETAILS:
- Reason for Report: {reason_text}
"""
        
        if reason == 'other' and other_reason:
            body += f"- Additional Details: {other_reason}\n"
        
        if user_ip:
            body += f"- Reporter IP: {user_ip}\n"
        
        body += f"""
Please review this report and take appropriate action if necessary.

This report was automatically generated by the ConnectYou Service Provider Directory.
"""
        
        # Log the report details instead of sending email for now
        logger.info(f"SERVICE PROVIDER REPORT")
        logger.info(f"Subject: {subject}")
        logger.info(f"Recipient: valuesnip.com@gmail.com")
        logger.info(f"Body: {body}")
        
        # For now, we'll return True to indicate the report was "processed"
        # In production, you'd implement actual SMTP sending here
        return True
        
    except Exception as e:
        logger.error(f"Error processing report: {str(e)}")
        return False