"""Add rating and review fields to Advertisement model

Revision ID: 03d1d7075428
Revises: 25d5e2017f41
Create Date: 2025-07-31 16:23:18.618024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d1d7075428'
down_revision = '25d5e2017f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.drop_column('review_text')
        batch_op.drop_column('review_count')
        batch_op.drop_column('star_rating')

    # ### end Alembic commands ###
