"""Initial migration

Revision ID: 05983f417e7d
Revises: 
Create Date: 2025-06-16 06:14:00.875456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05983f417e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_log', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'service_provider', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
