"""Added name field to AppDownloadTracking

Revision ID: 0c0a8d9cc065
Revises: 25bbaef3c0f2
Create Date: 2025-06-19 21:31:08.168629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0a8d9cc065'
down_revision = '25bbaef3c0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_download_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_download_tracking', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
