"""deleted is ishidden in City

Revision ID: 0cd5b0fcca3d
Revises: b5842f57cc81
Create Date: 2025-06-17 17:47:40.811990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd5b0fcca3d'
down_revision = 'b5842f57cc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
