"""added Category

Revision ID: 0e11a27900d1
Revises: a0de6597b3fa
Create Date: 2025-06-20 16:50:19.429061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e11a27900d1'
down_revision = 'a0de6597b3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
