"""added province field to ServiceProviderReport

Revision ID: 1331b4db845b
Revises: a129bad3f18e
Create Date: 2025-06-20 07:50:23.450158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1331b4db845b'
down_revision = 'a129bad3f18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('google_reviews_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('google_reviews_link')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('city')
        batch_op.drop_column('service')

    # ### end Alembic commands ###
