"""add google_place_id to service_provider

Revision ID: 175f9571cf92
Revises: 3d6558ab771a
Create Date: 2025-09-28 15:09:07.285878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175f9571cf92'
down_revision = '3d6558ab771a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_place_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_provider_google_place_id'), ['google_place_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_provider_google_place_id'))
        batch_op.drop_column('google_place_id')

    # ### end Alembic commands ###
