"""extend interaction log fields

Revision ID: 17a7dbf5f160
Revises: 03d1d7075428
Create Date: 2025-09-22 17:03:57.433612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a7dbf5f160'
down_revision = '03d1d7075428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('service_needed', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('client_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('client_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('service_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.drop_column('service_city')
        batch_op.drop_column('client_email')
        batch_op.drop_column('client_phone')
        batch_op.drop_column('service_needed')
        batch_op.drop_column('client_address')

    # ### end Alembic commands ###
