"""Add sub_city field to ServiceProvider

Revision ID: 25bbaef3c0f2
Revises: 0cd5b0fcca3d
Create Date: 2025-06-18 20:47:54.241325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bbaef3c0f2'
down_revision = '0cd5b0fcca3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_column('sub_city')

    # ### end Alembic commands ###
