"""Add description field to ChatIcon

Revision ID: 25d5e2017f41
Revises: 50b9f4aaadff
Create Date: 2025-07-18 15:25:34.522664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d5e2017f41'
down_revision = '50b9f4aaadff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_icons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_icons', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
