"""Notification migration re

Revision ID: 28e6c999fdeb
Revises: bc1db256c5a6
Create Date: 2025-06-16 07:19:50.868729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e6c999fdeb'
down_revision = 'bc1db256c5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.alter_column('rating_change',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.alter_column('rating_change',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
