"""Added name field to ServiceProviderReport

Revision ID: 31cfc8ef5b9e
Revises: 0c0a8d9cc065
Create Date: 2025-06-20 07:22:24.742817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cfc8ef5b9e'
down_revision = '0c0a8d9cc065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('primary_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('google_reviews_link', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.drop_column('report_reason')
        batch_op.drop_column('other_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('report_reason', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('additional_info')
        batch_op.drop_column('google_reviews_link')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('city')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('primary_email')
        batch_op.drop_column('service_category')

    # ### end Alembic commands ###
