"""interaction status fields

Revision ID: 3d6558ab771a
Revises: 72096a1e0952
Create Date: 2025-09-22 18:07:29.279915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6558ab771a'
down_revision = '72096a1e0952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='incomplete'))
        batch_op.add_column(sa.Column('status_note', sa.Text(), nullable=True))

    # Drop the server_default after backfilling existing rows
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.drop_column('status_note')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
