"""Added password field to ServiceProvider

Revision ID: 50b9f4aaadff
Revises: c295786566bf
Create Date: 2025-06-25 16:54:14.142767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b9f4aaadff'
down_revision = 'c295786566bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.drop_column('p_name')

    # ### end Alembic commands ###
