"""add referral_source to interaction log

Revision ID: 72096a1e0952
Revises: 17a7dbf5f160
Create Date: 2025-09-22 17:06:43.061142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72096a1e0952'
down_revision = '17a7dbf5f160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_source', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_log', schema=None) as batch_op:
        batch_op.drop_column('referral_source')

    # ### end Alembic commands ###
