"""Ensure is_hidden defaults to true

Revision ID: 81869d179bc3
Revises: bbf0a0686292
Create Date: 2025-06-17 07:43:38.552975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81869d179bc3'
down_revision = 'bbf0a0686292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_service_provider_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_service_provider_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('provider_phone', sa.VARCHAR(length=120), nullable=False),
    sa.Column('business_address', sa.VARCHAR(length=300), nullable=True),
    sa.Column('report_reason', sa.VARCHAR(length=50), nullable=False),
    sa.Column('other_reason', sa.TEXT(), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
