"""Added password field to ServiceProvider

Revision ID: 90960ea4bf5d
Revises: b225d8a0351d
Create Date: 2025-06-24 18:19:04.197123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90960ea4bf5d'
down_revision = 'b225d8a0351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
