"""removed province field to ServiceProviderReport

Revision ID: a129bad3f18e
Revises: a2119e117c5b
Create Date: 2025-06-20 07:41:41.836718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a129bad3f18e'
down_revision = 'a2119e117c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_reason', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('other_reason', sa.Text(), nullable=True))
        batch_op.drop_column('contact_email')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('service_category')
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('google_reviews_link')
        batch_op.drop_column('additional_info')
        batch_op.drop_column('primary_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('google_reviews_link', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('service_category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('other_reason')
        batch_op.drop_column('report_reason')

    # ### end Alembic commands ###
