"""Added province field to ServiceProviderReport

Revision ID: a2119e117c5b
Revises: 31cfc8ef5b9e
Create Date: 2025-06-20 07:28:55.064007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2119e117c5b'
down_revision = '31cfc8ef5b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.drop_column('province')

    # ### end Alembic commands ###
