"""Add nullable username to ServiceProvider

Revision ID: b225d8a0351d
Revises: 0e11a27900d1
Create Date: 2025-06-24 07:01:18.060981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b225d8a0351d'
down_revision = '0e11a27900d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
