"""Add is_hidden to ServiceProviderReport

Revision ID: bbf0a0686292
Revises: 28e6c999fdeb
Create Date: 2025-06-17 07:30:42.902816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf0a0686292'
down_revision = '28e6c999fdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
