"""Notification migration

Revision ID: bc1db256c5a6
Revises: c699d9427618
Create Date: 2025-06-16 07:02:14.644262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1db256c5a6'
down_revision = 'c699d9427618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.alter_column('review_change',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_change', schema=None) as batch_op:
        batch_op.alter_column('review_change',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
