"""Added password field to ServiceProvider

Revision ID: c1df04c93696
Revises: 90960ea4bf5d
Create Date: 2025-06-24 18:37:38.423234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1df04c93696'
down_revision = '90960ea4bf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email1', sa.String(length=120), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('email1')

    # ### end Alembic commands ###
