"""Added password field to ServiceProvider

Revision ID: c295786566bf
Revises: c1df04c93696
Create Date: 2025-06-24 20:40:20.186800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c295786566bf'
down_revision = 'c1df04c93696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
