"""added province field to ServiceProviderReport

Revision ID: ea69ec391db5
Revises: 1331b4db845b
Create Date: 2025-06-20 07:53:32.855628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea69ec391db5'
down_revision = '1331b4db845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
