"""Make is_hidden not nullable

Revision ID: eb01bf9d446b
Revises: 81869d179bc3
Create Date: 2025-06-17 07:44:32.548898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb01bf9d446b'
down_revision = '81869d179bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.alter_column('is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider_report', schema=None) as batch_op:
        batch_op.alter_column('is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
